### ISSUE TITLE
[question] event naming conventions

### ISSUE THREAD

**Issue by 43081j** [material-components/material-web#1042]
I've noticed a fair few components fire concisely named events such as `changed` but others fire mdc-namespaced events like `MDC:someEvent`.

to avoid confusion and people having to know what 'mdc' is, would it make more sense that events exposed by mwc stuff are _not_ namespaced but are just well named? or is there some underlying reason we have `MDC:opened` vs `opened`?

**Comment by asyncLiz** [comment]
The underlying reason is that we use MDC's foundation layer, which prefixes the events. The discussion of what events to fire and what to call them will happen in https://github.com/material-components/material-components-web-components/issues/616.

There is some ongoing work to slowly phase out the foundation layer, which will make event naming a more conscious choice. (See https://github.com/material-components/material-components-web-components/pull/1032 for the recent removal of the foundation from checkbox)

**Comment by dfreedm** [comment]
I think we're all in agreement to drop the `MDC:` prefix!

I'll turn this issue into a tracking issue for doing that in all the components.
