### ISSUE TITLE
Add missing icon/helper-text foundation features to textfield

### ISSUE THREAD

**Issue by asyncLiz** [material-components/material-web#1215]
**Is your feature request related to a problem? Please describe.**
`<mwc-textfield>` does not use the MDCHelperTextFoundation or MDCIconFoundation. Both of these classes offer features that are missing and should be added:

Helper Text
- announcement to screen readers

Icon
- Interactivity (focus, click events, disabled)
- Aria labels

**Describe the solution you'd like**
Helper text should toggle `role="alert"` when appropriate to announce to screen readers.

Add the following properties for icons:

- `iconAriaLabel` *
- `iconInteractive` *
- `trailingIconAriaLabel`
- `trailingIconInteractive`

* Discuss with design, leading icons might only be allowed to be decorative

Dispatch the following events when an interactive icon is clicked:

- `@iconclick`
- `@trailingiconclick`

**Describe alternatives you've considered**
We could instead implement the foundations for each of these, but this would conflict with future internal tooling which would need to remove the foundations anyway.

**Additional context**
MDC foundation links:
- https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/helper-text/foundation.ts
- https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/icon/foundation.ts

**Comment by DrewLandgraveCbsi** [comment]
Ran across this today. Any idea on when this could be addressed?

**Comment by DrewLandgraveCbsi** [comment]
Any update on the interactivity portion of this request?

**Comment by christophe-g** [comment]
In light of the approach  proposed in #893 by @dfreedm , is the integration of MDCHelperTextFoundation still the preferred approach or is it not simpler to handle the logic of `aria-hidden`, `role=alert`, `aria-describedby` accessibility attributes directly in the render function?

I am asking because I tried to add and integrate a MDCHelperTextFoundation adapter to textfield (because I need more accessible fields like ... now) and am under the impression that hooking adapters into the component makes things unnecessary bloated. 

Lit-element provides us with flexible and expressive ways to make UI depend on state. As a developer, I have the impression I am loosing that under the current implementation, with no obvious benefit (but I might miss smth).

**Comment by asyncLiz** [comment]
@christophe-g this issue plans to add these features directly to the component _without_ the use of MDCHelperTextFoundation or MDCIconFoundation:

> **Describe alternatives you've considered**
We could instead implement the foundations for each of these, but this would conflict with future internal tooling which would need to remove the foundations anyway.

**Comment by christophe-g** [comment]
Ah, great thank you. I'll go the same path.

**Comment by christophe-g** [comment]
@asyncLiz - any change to get #1852 reviewed ?

**Comment by yinonov** [comment]
Icon interactivity is quite a big deal in many designs. this has been long awaited feature for us. is there a PR in process? if this is a material web component dedicated solution and not part of mdc, will it be applicable to PR this feature?

**Comment by asyncLiz** [comment]
Obsolete with Material 3 text field
