### ISSUE TITLE
Tab inactive text label doesn't use theme colors

### ISSUE THREAD

**Issue by ronnyroeller** [material-components/material-web#1480]
**Describe the bug**
The color of inactive tabs (`--mdc-tab-text-label-color-default`) is fixed to `rgba(0, 0, 0, 0.6)`. This means the color doesn't adjust when changing the theme (e.g. for dark mode).

**Expected behavior**
I would have expected that `--mdc-tab-text-label-color-default` derives its value from `--mdc-theme-text-secondary-on-background` (or `--mdc-theme-text-secondary-on-surface` - the [spec](https://material.io/components/tabs#theming) isn't really clear on this):
![image](https://user-images.githubusercontent.com/9339055/86129250-af05f580-bae2-11ea-8dad-1f82b93c8185.png)

**Screenshots**
Tabs with [Material default dark theme](https://material.io/design/color/dark-theme.html#ui-application):

![image](https://user-images.githubusercontent.com/9339055/86129310-c513b600-bae2-11ea-9fc9-0bd9e07e8f43.png)

**Workaround**

Explicitely set inactive color:
```css
:host {
  --mdc-tab-text-label-color-default: var(--mdc-theme-text-secondary-on-background);
}
```

**Comment by asyncLiz** [comment]
Thanks for the issue! You're right that the tab should inherit colors from `on-surface`, but this is currently blocked by https://github.com/material-components/material-components-web/issues/5784 since we don't have `on-surface` custom properties yet.

Once we have those in the upstream, we'll be able to remove this custom property in favor of the generic theming property.
