### ISSUE TITLE
Clipped Drawer

### ISSUE THREAD

**Issue by a11delavar** [material-components/material-web#2028]
**Is your feature request related to a problem? Please describe.**
I would like to see a clipped version of the drawer.
Currently I achieve this partially via extending the Drawer's `styles` and restructuring the application root, so that `mo-top-app-bar` wraps the `mdc-drawer`, not other way around.
This has drawbacks, e.g. the auto-collapse of `mwc-top-app-bar` does not work on page scroll, and it behaves as it were a `mwc-top-app-bar-fixed`.

**Describe the solution you'd like**
Material guideline already has all things documented [here](https://material.io/components/navigation-drawer#standard-drawer)

![image](https://user-images.githubusercontent.com/38350963/103139073-d2e47580-46d8-11eb-8d5b-531476164937.png)

Eventually, the `type` property of the `mwc-drawer` should also contain `clipped`.

**Comment by e111077** [comment]
Hello, I believe this is already in progress in the drawer rewrite.

**Comment by 3mo-arshia** [comment]
Cool! Looking forward to see it!

**Comment by arshia11d** [comment]
Cool! looking forward to see it.

**Comment by yinonov** [comment]
will the rewrite issue the drawer in such way it could act as a root level application layout?

- aside should be full block size of it's parent, or in application root - min block size of fit-content

- scrolling should scroll the document body and not the drawer's content itself

- the above should trigger block size change with the existence of top-app-bar

**Comment by arshia11d** [comment]
> scrolling should scroll the document body and not the drawer's content itself

Does that mean that the Drawer won't have internal content scrolling? I am not sure I expect this, currently if I have a long list in my drawer, the scrolling works fine.

**Comment by yinonov** [comment]
> > scrolling should scroll the document body and not the drawer's content itself
> 
> Does that mean that the Drawer won't have internal content scrolling? I am not sure I expect this, currently if I have a long list in my drawer, the scrolling works fine.

ure right by my ask is for a _root level application layout_ support, which drawer seems like matching almost all aspects. especially with integrating `mwc-top-APP-bar`

**Comment by yinonov** [comment]
What I expect from drawer in an application context is that

1. its aside should have fixed block size and have scrolling behavior
2. refrain content region from being a coupled part of the component due to its scrolling boundaries. the scrolling of the pages become part of a div, not sure why, but I dont feel comfortable with it. plus, if adding a top-bar, it overlays the scrollbar which is kind of a style bug

just ran into [this](https://www.bbc.co.uk/gel/guidelines/side-drawer-menu) the other day. it's the bbc design pattern of drawer, where they seem to only focus on the aside part itself as drawer. excluding the content from being an integral part.

guessing it's opinionated, but has this ever been discussed? I mean is this a valid design controversy?
