### ISSUE TITLE
[mwc-drawer] Type modal only suitable for fullpage layout

### ISSUE THREAD

**Issue by JaySunSyn** [material-components/material-web#271]
The drawer on type modal is `position: fixed` with `left: 0`. This makes it only usable for full page layouts but not for nested use cases or use cases where the drawer is part of an app's sub section.

**Comment by azakus** [comment]
Can you explain your use-case for having a drawer as a subcomponent? A screenshot of your setup would be helpful.

I think the intent of the modal type is to require interaction when the drawer is open.

**Comment by JaySunSyn** [comment]
Sure, my use case is a nested drawer layout.

![image](https://user-images.githubusercontent.com/5872432/68461948-c0c12280-020b-11ea-9895-c04a5bbe99ea.png)


![image](https://user-images.githubusercontent.com/5872432/68461981-d3d3f280-020b-11ea-962a-9548312bb957.png)

**Comment by fgirardey** [comment]
Using `position: fixed;` on `<mwc-drawer>` would also make possible to use the `document.scrollingElement` to scroll into the page on full page layout.

By doing so it save dozens of composite layers because when there is a `<mwc-list-item>` element in the content (because of the `overflow: hidden` applied on it).

`position: fixed` would definitely increase performances.

**Comment by asyncLiz** [comment]
Obsolete in M3
