### ISSUE TITLE
Question about changes to expect

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-web#2946]
> Components with variant attributes will be split into several variant components:
>
> Example: mwc-button will be split into md-text-button, md-filled-button, md-tonal-button, md-outlined-button, etc

Hey, 

Thanks for informing us about the upcoming changes, it is appreciated. 

I am curious to know what advantages this particular change bring to a consumer of material-web. Will there still be a generic `md-button`?

Consider this use-case: 

![image](https://user-images.githubusercontent.com/1168053/143831189-bfba7cf3-c497-4a3c-b7b1-ab3524c8a4a1.png)

It feels very natural to write smth like (hence, consider a button to be **one** entity that takes various form depending on the context): 

```js 
[...languages].map(lan => html`
  <mwc-button 
    .unelevated=${this.lan === lan.$key} 
    .outlined=${this.lan !== lan.$key} 
    .label=${lan.label}></mwc=button>`
```

**Comment by asyncLiz** [comment]
The advantage it gives is being able to split styles across variants.

For example, `<mwc-textfield>` includes styles for both the filled and outlined variants, and is one of our heavier components byte-wise because of it. Many applications do not use both variants, but choose one or the other. Splitting into `<md-filled-textfield>` and `<md-outlined-textfield>` allows each variant to only load the styles required.

Additionally, under the hood setting a variant attribute would re-render a lot of DOM, since some variants are drastically different from each other. So while it may seem more performant to change an attribute, in reality it's not much different than rendering a different web component.

There won't be a generic `<md-button>`, but you could make your own for use within your app!

```
@customElement('md-button')
class MyButton extends LitElement {
  @property({type: Boolean}) outlined = false;
  
  render() {
    if (this.outlined) {
      return html`<md-outlined-button></md-outlined-button>`;
    }
    
    return html`<md-filled-button></md-filled-button>`;
  }
}
```
