### ISSUE TITLE
Best way to access underlying field

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#2973]
For instance, how do I access the raw `<input>` field in `<mwc-textfield>`?

**Comment by asyncLiz** [comment]
Hi! We do not support directly accessing the internal DOM of our components.

**Comment by treeder** [comment]
Why not?

**Comment by treeder** [comment]
And for those that come across this, it is actually supported and you can access it via `.formElement`.

**Comment by asyncLiz** [comment]
> Why not?

The internal DOM is encapsulated behind a shadow root. It's an implementation detail of the web component, not a public API.

> And for those that come across this, it is actually supported and you can access it via `.formElement`.

Keep in mind that this is not supported since `.formElement` is a [protected property](https://github.com/material-components/material-web/blob/e1bcf14eb92b2d8f62fdcc5f2e320ccce530109e/packages/base/form-element.ts#L48). Relying on it or other internal implementation details may break your code in non-breaking updates.
