### ISSUE TITLE
Inputs in top app bar do not display correctly

### ISSUE THREAD

**Issue by hello-smile6** [material-components/material-web#3276]
**Describe the bug**
If an `<mwc-textfield>` is in the top app bar, it does not display correctly. Additionally, buttons in the top app bar are unusable.

**To Reproduce**
```html
<!DOCTYPE html>
<mwc-top-app-bar>
<mwc-textfield></mwc-textfield>
</mwc-top-app-bar>
<script type="module">
import "https://unpkg.com/@material/mwc-top-app-bar?module";
import "https://unpkg.com/@material/mwc-textfield?module";
</script>
```

**Expected behavior**
I expected that I would be able to move my webpage's UI into the top bar.

**Screenshots**

**Browser Version (please complete the following information):**
 - OS: Chrome OS ([Octopus](https://cros.tech/device/octopus))
 - Browser: Chrome
 - Version: 99.0.4844.57 with update pending (Strange, since the latest version is 99.0.4844.57)

**Additional context**
There is a similar issue with `<mwc-button>`.

**Comment by asyncLiz** [comment]
This is actually WAI, since the Material 2 spec does not allow for text fields in the top app bar.

However, you can achieve this by adding the text field to the `slot="title"` or `slot="actionItems"` slots: https://jsbin.com/rafiyuhovi/edit?html,output

If you want more customization, I'd recommend extending the top app bar and creating your own component that adds this functionality!
