### ISSUE TITLE
Dynamic theme material you

### ISSUE THREAD

**Issue by danilotomaccio** [material-components/material-web#3394]
**Premise:** I know that this feature is not strictly about components but is more about browsers but I have not been able to find any other information and this seems to me the closest place to the feature

**Is your feature request related to a problem? Please describe.**
Inability to use Android 12 dynamically generated colors in my web app

**Describe the solution you'd like**
I don't know if browsers currently expose (and/or plan to) CSS variables to access the dynamically created theme colors from Android. If not, the ideal would be to have CSS variables. It would then be great if the default values of the components were aligned with those of the system

**Describe alternatives you've considered**
If not system colors, it would be great if the components were at least aligned with the variables generated by the [Material Theme Builder tool](https://material-foundation.github.io/material-theme-builder/#/custom)

**Additional context**
I tried the dynamic theme on my Pixel 6 Pro and I must say that the consistency and union between the various apps given by the theme greatly improves the experience and it would be a shame not to be able to extend it to websites and PWAs

**PS:**
If someone should be aware of issues or tickets, even of other projects (e.g. chrome, chromium, etc.), related to the feature the links would be welcome

**Comment by asyncLiz** [comment]
Hi! This is a pretty broad topic for how we want to handle this on the web and coordinate with platforms like Chrome to handle dynamic color (aka Material You).

Dynamic theming _is_ possible with the [`--md-sys-color-*` custom properties](https://github.com/material-components/material-web/blob/056b3ceffbe2fe3408dbdbb319932da85637e779/components/tokens/latest/_md-sys-color.scss#L26), but how this API will look like for end users is still being discussed.

I'm going to leave this open to track dynamic color support on the web for Material 3 since it's slightly different than https://github.com/material-components/material-web/issues/3050 for M3 availability.

**Comment by omar2205** [comment]
hey @asyncLiz, can you enable discussions in this repo? I feel this is more of a discussion than it's an issue.

**Comment by asyncLiz** [comment]
Closing since discussions are enabled and we have basic theming docs
