### ISSUE TITLE
Radio, Switch, Formfield alignment issues

### ISSUE THREAD

**Issue by aomarks** [material-components/material-web#380]
I tried what seemed to be a pretty straightforward layout of some selection controls using flex:

```html
<style>
  section {
    display: flex;
    flex-direction: column;
  }
</style>

<section>
  <mwc-formfield label="Checkbox"><mwc-checkbox></mwc-checkbox></mwc-formfield>
  <mwc-formfield label="Checkbox"><mwc-checkbox></mwc-checkbox></mwc-formfield>

  <mwc-formfield label="Radio"><mwc-radio></mwc-radio></mwc-formfield>
  <mwc-formfield label="Radio"><mwc-radio></mwc-radio></mwc-formfield>

  <mwc-formfield label="Switch"><mwc-switch></mwc-switch></mwc-formfield>
  <mwc-formfield label="Switch"><mwc-switch></mwc-switch></mwc-formfield>
</section>
```

Which renders like this:

<img width="147" alt="Screen Shot 2019-08-16 at 4 59 58 PM" src="https://user-images.githubusercontent.com/48894/63204115-7b94b680-c049-11e9-86ca-96b4b89a186e.png">

Here it is at 2X scale, with lines added to show some of the issues:

<img width="294" alt="Screen Shot 2019-08-16 at 4 59 58 PM 2" src="https://user-images.githubusercontent.com/48894/63204116-7cc5e380-c049-11e9-925d-7b294b2c9d30.png">

1) The switch label is not horizontally aligned with the radio and checkbox labels (green line).
2) The radio label is not vertically aligned with the radio button (red line).
3) The switch label is not vertically aligned with the switch (red line).
4) Switches have significantly less vertical margin than checkboxes or radios (pink line).
5) Checkboxes and radios have similar vertical margin, but not quite the same (pink line).

I think we should test this out using core MDC, to see if the same issues exist.

It's possible this is how MDC is designed, in which case we need to provide some additional help for users to get a decent layout: a helper element, some exported styles, or at the very least some documentation.

(But my initial reaction, whatever the cause, was that it seems like these components should tend to align themselves naturally by default, by having consistent sizes and margins).

**Comment by dfreedm** [comment]
Related #1037 for Switch

**Comment by asyncLiz** [comment]
Notably the horizontal alignment was solved in switch by setting the `:host` to `display: inline-flex;`.

**Comment by asyncLiz** [comment]
A note on this, we need to investigate what to do with switch in formfield. Right now we are [adding styles](https://github.com/material-components/material-components-web-components/blob/c0a5741cf3fc659b58b93344b4b63e56ef0c023a/packages/formfield/src/mwc-formfield.scss#L29-L34) to make the switch appear visually similar to checkbox and radio, but this is not how MDC aligns the switch.

![Screen Shot 2020-04-06 at 11 55 36 AM](https://user-images.githubusercontent.com/34382620/78594646-8c26b680-77fd-11ea-8004-742b9bb64d19.png)

This is how the switch appears when removing those styles (correct, how MDC works). The issue is the touch target of switch is different than the touch target of checkbox and radio, which is why they visually appear different.

A better solution may be to allow users to customize the padding of the label. That way they may customize different controls with different widths to be in alignment according to their widths.

**Comment by asyncLiz** [comment]
Obsolete with M3, there is no longer a formfield component. Instead, use a `<label>` and CSS positioning to align things
