### ISSUE TITLE
md-dialog height is wrong on Chrome on Android (address bar issue)

### ISSUE THREAD

**Issue by rbjarnason** [material-components/material-web#4080]
md-dialog height is wrong on Chrome on Android where the footer is not visible and if there is scrollable content the user is stuck without getting to for example an exit button in the footer.

![image](https://user-images.githubusercontent.com/43699/227051898-5bdf27f4-d28a-413a-a1c8-5ac0fd3dce92.png)

**Comment by sorvell** [comment]
Good catch! See [discord thread](https://discord.com/channels/1012791295170859069/1087872065459196042).

I noted a few problems when [investigating](https://lit.dev/playground/#gist=3e7fd4b8b2c6cdc9d2550a13b6ff1848). 
* sizes in the dialog are using `vh` instead of `dvh`: this should just be changed.
* in fullscreen mode, the settable container tokens are not honored: probably should just remove this.
* dialog appears to apply a default `inset-block-start`: probably will need to change the default when in fullscreen mode.

Workaround until fixed which I believe should work:
```
md-dialog[showing-fullscreen] {
  /* hack: private! */
  --_container-max-block-size: 100dvh;
  --md-dialog-container-inset-block-start: 0px;
}
```

**Comment by rbjarnason** [comment]
Workaround works perfectly, thanks! :) Will remove hack after this gets fixed.
