### ISSUE TITLE
Provide a proper ESM build for CDNs

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#4094]
Using jsdelivr's ESM feature, I get these types of errors:

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "md-focus-ring" has already been used with this registry
```

The same thing happens in the prior mwc version too.

**Comment by treeder** [comment]
Example:

```html
<html>
<body>
<script type="module">
import 'https://cdn.jsdelivr.net/npm/@material/web@1.0.0-pre.5/navigationtab/navigation-tab.js/+esm'
import 'https://cdn.jsdelivr.net/npm/@material/web@1.0.0-pre.5/button/filled-button.js/+esm'
</script>
<h1>Hi</h1>
</body>
</html>
```

**Comment by omar2205** [comment]
Try this
```html
<script type="module">
import 'https://esm.run/@material/web@1.0.0-pre.5/button/outlined-button.js'
</script>
<md-outlined-button label="Back"></md-outlined-button>
```

**Comment by omar2205** [comment]
Try unpkg with `?module`
```
import 'https://unpkg.com/@material/web@1.0.0-pre.5/button/outlined-button.js?module'
import 'https://unpkg.com/@material/web@1.0.0-pre.5/button/filled-button.js?module'
```

**Comment by treeder** [comment]
Unpkg seems to handle it better, thanks @omar2205 👍

**Comment by treeder** [comment]
@asyncLiz were you able to try that example and reproduce it?

**Comment by asyncLiz** [comment]
Unfortunately CDNs are not something we have capacity to investigate support for. Our recommendation is still to use npm to download this library for use.

**Comment by treeder** [comment]
I'm not saying to do anything with a CDN, I'm just saying to provide a proper ESM/module build then the CDN's don't have to do anything but deliver what you've provided. 

For instance, Lit itself does this here: https://github.com/lit/dist/tree/v2.7.1

And is available via CDNs without any extra processing by the CDNs, for example: https://cdn.jsdelivr.net/gh/lit/dist@2.7.1/

Which is found in the Lit docs: https://lit.dev/docs/getting-started/#use-bundles

**Comment by asyncLiz** [comment]
Correct. We don't have cycles to add or review creating bundles right now. I'm leaving this issue open though for a future feature :)

**Comment by treeder** [comment]
Looks like import maps are available in all browsers now: https://www.infoq.com/news/2023/04/import-maps-generally-available/ 🚀

**Comment by asyncLiz** [comment]
We have bundles available now :)

https://unpkg.com/@material/web/all.js
https://unpkg.com/@material/web/common.js

**Comment by treeder** [comment]
For others that find this and don't want to pull in bundles, you can use import maps and just use specific components directly without any build process or anything: https://thingster.app/things/ctUhszB47Wb52JgHeMV9m

**Comment by philter87** [comment]
That is pretty awesome @treeder. It seems I have a serious hole in my knowledge pool. I had no idea of what "import maps" is. 

Should this be part of official documentation? Either as part of: 
1. Quick start: https://github.com/material-components/material-web/blob/main/docs/quick-start.md 
2. FAQ section: https://github.com/material-components/material-web/blob/main/docs/support.md

Or is too premature?

I have spend a lot of time digging through the documentation and couldn't find anything. I want to help others in the same situation. (We are actually using beercss now because I was unable to find anything, but now I might move to material/web )

**Comment by philter87** [comment]
Thanks :) I managed to get it working from you previous sample as well, but nice with everything bundled together as I was also struggling a bit with changing the font to Inter. 

I added the second comment to asyncLiz, because I was just wondering if it was suppose to work without the 'importmaps' if the entire bundle was imported. But I don't think it does. 

And should I add your sample to the documentation?

**Comment by asyncLiz** [comment]
When using unpkg.com, you may also need import maps for lit and tslib since it doesn't bundle things. If you're looking for a simple esm bundle from a cdn, use https://esm.run

```html
<script type="module" src="https://esm.run/@material/web/all.js"></script>

<md-outlined-button>Material</md-outlined-button>
<md-checkbox></md-checkbox>
```

https://jsbin.com/cagevofoli/edit?html,output

You also only need `all.js` or `common.js`. Loading both will load two duplicate bundles, and you'll get errors.

**Comment by philter87** [comment]
Awesome! I did not know about esm.run either. And silly me to import "common" and "all" :)

**Comment by omar2205** [comment]
> Awesome! I did not know about esm.run either. And silly me to import "common" and "all" :)

You could say this is a _common_ mistake 😅
