### ISSUE TITLE
[md-menu] "Unknown promise rejection reason" when trying to close a menu through the anchor button.

### ISSUE THREAD

**Issue by nangelovv** [material-components/material-web#4544]
The button and the menu work as intended when being closed by clicking anywhere else on the screen or in the menu itself, but when the button is pressed to close the menu the following error shows up "surfacePositionController.ts:316 Uncaught (in promise) undefined"

This is using JavaScript and React, no TypeScript.

` 
var menuRef = useRef();
var menuButton = useRef();

<div style={{position: "relative"}}>

        <md-text-button ref={menuButton} onClick={() => {menuRef.current.open ? menuRef.current.open = true : menuRef.current.open = true}}>
          Open Menu
        </md-text-button>

        <md-menu ref={menuRef}>

          <md-menu-item
            headline={"One"}>
          </md-menu-item>

          <md-menu-item
            headline={"Two"}>
          </md-menu-item>
        </md-menu>
`

**Comment by juanpmarin** [comment]
@nangelovv did you find a solution for this? I have the same issue but with select

**Comment by nangelovv** [comment]
@juanpmarin Yeah, turns out that when the menu is opened - it's "open" state/attribute could be equal to anything but null, so when I was trying to close the menu, I was always trying to set open={false}, but for some amazing and unexplainable to me reason, Google chose to make it so in order for the menu to be closed, it needed to be open={null}. That's the logic for a lot of the elements in MD3, the switch operates on the same principle, if it's anything but null, it will be turned on, but if it's null, it will be switched off.

**Comment by asyncLiz** [comment]
This is an unfortunate quirk of how React works with setting boolean attributes. React renders `<md-menu open="false">` instead of `<md-menu>` when you set the prop to `false`.

In order to not add the attribute, React requires using `null`.

Have you tried using Lit's [React wrapper generator](https://lit.dev/docs/frameworks/react/)? It should solve many of these quirks for you with react component wrappers.

**Comment by asyncLiz** [comment]
Also if you're curious as to why, our components mimic native elements! Setting `<input type="checkbox" checked="false">` will also result in a selected checkbox instead of an unselected one.

React has special handling for known boolean attributes, but it doesn't know how to handle elements it hasn't been told about.
