### ISSUE TITLE
If you have a select in md-dialog, it won't expand or show a scroller so you can't see the values

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#4812]
eg:

![image](https://github.com/material-components/material-web/assets/75826/6d41800c-61f4-47fa-8a36-584aca21fe96)

**Comment by asyncLiz** [comment]
@e111077 are there any select-specific features like fixed menus or something that would help with this use case?

**Comment by e111077** [comment]
Workaround for now is to set `<md-select menu-fixed>` attribute on select.

This is an issue that is unfortunately going to have to be truly fixed by browser native popover.

**Comment by e111077** [comment]
@asyncLiz testing this out, there seems to be an issue where even with fixed the actions bar is rendered above the menu. It seems that the scroller needs a `z-index` >= 1

https://lit.dev/playground/#gist=a21cae6b3c4fa1249a1a9e99cb1cf783

**Comment by asyncLiz** [comment]
`z-index: 1` on the scroller would be a good fix. It needs a z-index >= 0 to appear on top of the background is all

**Comment by e111077** [comment]
Sorry, I didn't see the call for a PR, so I have a PR out with tests running internally rn:

#4829

**Comment by treeder** [comment]
Did your fix make it into 1.0 @e111077 ?  Doesn't appear to have.

**Comment by Bob1k** [comment]
in 1.0 lib version to show over dialog should add `menu-positioning="fixed"` to md-select

**Comment by e111077** [comment]
Sorry about the lack of update. Yes, but as @Bob1k said, it uses a new attribute. This is because we eventually have plans to have `menu-positioning="top-layer"` (or `"document"` not quite sure on the naming just yet) for the upcoming `popover` API + anchoring API.

Our friends at Chrome OS (since they only need to support Chrome) are intending to test out menu + popover + anchoring for us.

This should provide a true answer to this problem rather than a workaround
