### ISSUE TITLE
Why doesn't Chip "remove" event bubble?

### ISSUE THREAD

**Issue by datvm** [material-components/material-web#4905]
Here's the code: https://github.com/material-components/material-web/blob/c26a578448666fda50eb2b25be59b88390e32097/chips/internal/trailing-icons.ts#L47C39-L47C39

```ts
function handleRemoveClick(this: Chip, event: Event) {
  if (this.disabled) {
    return;
  }

  event.stopPropagation();
  const preventDefault =
      !this.dispatchEvent(new Event('remove', {cancelable: true}));
  if (preventDefault) {
    return;
  }

  this.remove();
}
```

In comparison to the other `selected` event, this one does not bubble at all. Is there any reason why?

This would cause an issue with SPA frameworks like Blazor or React. See https://github.com/dotnet/aspnetcore/issues/39831#issuecomment-1024304085

Update: as I work through the components, many others don't, like all 5 events of `md-dialog`.

**Comment by asyncLiz** [comment]
React can still listen to non-bubbling events (it does so with props like `onChange` or imperatively like `ref.addEventListener()`).

We don't bubble events that are not intended for usage beyond the parent controlling it. This helps with events leaking to other elements and causing side effects.

Chip only needs to inform someone that controls it as to whether or not it is removed, which is why it doesn't bubble, like `click` does.

Hope that explains why! If Blazor does not hook into non-bubbling events, like `change` or `focus`, then you may want to consider extending or wrapping the elements and re-dispatching bubbling versions of events that the framework needs.

**Comment by datvm** [comment]
Thanks for the explanation. While I disagree (for example, standard HTML `<input>` bubbles its `change` or `click` events), I respect the team's decision.

I will leave the code I am using to solve it in case you absolutely need the event to bubble. It works by overriding `dispatchEvent` method and checking if the event is from a `<md-*>` tag and bubbling it if it doesn't.

```js
#overrideDispatch() {
    const original = EventTarget.prototype.dispatchEvent;

    EventTarget.prototype.dispatchEvent = function (event) {
        let arg = event;

        if (!event.bubbles && this.tagName?.startsWith("MD-")) {
            arg = new CustomEvent(event.type, {
                bubbles: true,
                detail: event.detail,
                cancelable: event.cancelable,
                composed: event.composed,
            });
        }

        return original.call(this, arg);
    }
}
```
