### ISSUE TITLE
[Feature Request] Prevent dialog from closing when clicking outside of it

### ISSUE THREAD

**Issue by datvm** [material-components/material-web#5059]
### Description

Right now there is `type="alert"` though I am not really sure what it does:

> Alerts  
> Add a [type="alert"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alertdialog_role) attribute to dialogs that need to communicate an important message and require a user's response.

Adding that doesn't really change anything for me. It's under Accessibility section so I assume it's only for screen readers and not actually prevent the dialog from closing.

Can we have an option, maybe `modal` attribute that prevent dialog from closing when tapping outside?

**Comment by asyncLiz** [comment]
You're correct, `type="alert"` is only for screen reader accessibility. It changes the type of dialog that is read to the user.

You can call `preventDefault()` on the `cancel` event to stop the dialog from closing due to cancel gestures, like the escape key and clicking the background.

```js
dialog.addEventListener('cancel', event => event.preventDefault());
```

Hope that helps! :)
