### ISSUE TITLE
Add "active-tab-index" attribute support for Tabs?

### ISSUE THREAD

**Issue by datvm** [material-components/material-web#5297]
### Description

I think [Lit Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL2FsbFwiIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxtZC10YWJzIGFjdGl2ZS10YWItaW5kZXg9XCIxXCI-XG4gICAgPG1kLXByaW1hcnktdGFiPlRhYiAxPC9tZC1wcmltYXJ5LXRhYj5cbiAgICA8bWQtcHJpbWFyeS10YWI-VGFiIDI8L21kLXByaW1hcnktdGFiPlxuICA8L21kLXRhYnM-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMy4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4yLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeNC4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjMuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d) should work for `<md-tabs>` similar to `<md-select>`'s `selected-index`:

```
  <md-tabs active-tab-index="1">
    <md-primary-tab>Tab 1</md-primary-tab>
    <md-primary-tab>Tab 2</md-primary-tab>
  </md-tabs>
```

This would make life much easier for a lot of Web frameworks where it's much harder to access DOM property than HTML attributes.

**Comment by asyncLiz** [comment]
I think the request is reasonable, but are there pain points to setting the `active` attribute on the selected tab? In general that's where the source of truth should be.

```html
<md-tabs>
  <md-primary-tab>Tab 1</md-primary-tab>
  <md-primary-tab active>Tab 2</md-primary-tab>
</md-tabs>
```

The parent's active tab index is more expensive than its children, since it will look up and set the child's attribute. Select is the same way, and discourages using `selected-index` for things like SSR.

**Comment by datvm** [comment]
Thanks for the suggestion, I can't recall now what issue I ran into trying to use `active` on individual tabs but at least one problem is that there is no animation when using it [Lit Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL2FsbFwiIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxtZC10YWJzIGFjdGl2ZS10YWItaW5kZXg9XCIxXCI-XG4gICAgPG1kLXByaW1hcnktdGFiPlRhYiAxPC9tZC1wcmltYXJ5LXRhYj5cbiAgICA8bWQtcHJpbWFyeS10YWIgYWN0aXZlPlRhYiAyPC9tZC1wcmltYXJ5LXRhYj5cbiAgPC9tZC10YWJzPlxuICBcbiAgPHA-XG4gICAgPGJ1dHRvbj5Td2l0Y2ggVGFiPC9idXR0b24-XG4gIDwvcD5cbiAgXG4gIDxzY3JpcHQ-XG4gICAgY29uc3QgdGFic0VsID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcIm1kLXRhYnNcIik7XG4gICAgY29uc3QgdGFicyA9IFsuLi5kb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxsKFwibWQtcHJpbWFyeS10YWJcIildO1xuICAgIFxuICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCJidXR0b25cIikuYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsICgpID0-IHtcbiAgICAgIGNvbnN0IGN1cnJUYWIgPSB0YWJzRWwuYWN0aXZlVGFiSW5kZXg7XG4gICAgICB0YWJzWzEgLSBjdXJyVGFiXS5zZXRBdHRyaWJ1dGUoXCJhY3RpdmVcIiwgXCJcIik7XG4gICAgICB0YWJzW2N1cnJUYWJdLnJlbW92ZUF0dHJpYnV0ZShcImFjdGl2ZVwiKTtcbiAgICB9KTtcbiAgPC9zY3JpcHQ-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMy4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4yLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeNC4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjMuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d):

```
  <md-tabs active-tab-index="1">
    <md-primary-tab>Tab 1</md-primary-tab>
    <md-primary-tab active>Tab 2</md-primary-tab>
  </md-tabs>
  
  <p>
    <button>Switch Tab</button>
  </p>
  
  <script>
    const tabsEl = document.querySelector("md-tabs");
    const tabs = [...document.querySelectorAll("md-primary-tab")];
    
    document.querySelector("button").addEventListener("click", () => {
      const currTab = tabsEl.activeTabIndex;
      tabs[1 - currTab].setAttribute("active", "");
      tabs[currTab].removeAttribute("active");
    });
  </script>
```

Also in reactive frameworks, _usually_ it's a bit awkward to use `active` since we need to keep track of the index in a `for` loop like this (pseudo-code):

```razor
@{
    var counter = 0;
}

<md-tabs>
    @foreach (var tab of tabs)
    {
        var z = counter++;
        <md-tab label="@(tab.Title)" active="@(z == currTabIndex)"></md-tab>
    }
</md-tabs>
```

**Comment by adrianjost** [comment]
I agree and expected this behaviour based on the properties [defined in the docs](https://material-web.dev/components/tabs/#properties).
I'm using the bundled version from npm and was able to get it running by just adding the following patch:
```diff
diff --git a/node_modules/@material/web/tabs/internal/tabs.js b/node_modules/@material/web/tabs/internal/tabs.js
index 801d980..a2844e6 100644
--- a/node_modules/@material/web/tabs/internal/tabs.js
+++ b/node_modules/@material/web/tabs/internal/tabs.js
@@ -270,6 +270,9 @@ export class Tabs extends LitElement {
 __decorate([
     queryAssignedElements({ flatten: true, selector: '[md-tab]' })
 ], Tabs.prototype, "tabs", void 0);
+__decorate([
+    property({ type: Number, attribute: 'active-tab-index' })
+], Tabs.prototype, "activeTabIndex", void 0);
 __decorate([
     property({ type: Boolean, attribute: 'auto-activate' })
 ], Tabs.prototype, "autoActivate", void 0);
```

It looks like everything that is necessary to get it working is already there, there is just a binding to the outer world missing.

For the `active` prop on the `tab` elements themself, there exists a [`@property({type: Boolean, reflect: true}) active = false;`](https://github.com/material-components/material-web/blob/main/tabs/internal/tab.ts#L54).
I'm just getting started learning `lit`, but I would expect a similar `@property({type: Number, reflect: true})` added to [` set activeTabIndex(index: number)`](https://github.com/material-components/material-web/blob/main/tabs/internal/tabs.ts#L69) to do just this.
Hadn't had time to test they yet though, because I didn't have this project setup yet.
