### ISSUE TITLE
Radio throws error and hydrates tabindex in some hydration scenarios

### ISSUE THREAD

**Issue by einarstubhaug** [material-components/material-web#5398]
### What is affected?

Component

### Description

When I try to use radio buttons it fails with error messages.
In Chrome:  _Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes_
Firefox: Uncaught DOMException: Operation is not supported

### Reproduction

https://stackblitz.com/edit/webpack-webpack-js-org-slhiao?file=dist%2Findex.html

### Workaround

I have not found a workaround

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing in 1.1.1

### Browser/OS/Node environment

Latest Chrome, Mac Sonoma, Node 20.10.0

**Comment by asyncLiz** [comment]
Hmm interesting! Ultimately this is failing because of a `tabindex` attribute. We set the tabindex after [`queueMicrotask()`](https://github.com/material-components/material-web/blob/4b4c373a6b9ff28f4acf604335701228525c3b84/labs/behaviors/focusable.ts#L80-L83) to try and set it as soon as possible after construction.

This may not be long enough in some situations. We could use a `setTimeout()` to wait a full task. When I update your compiled `main.js` and replace `queueMicrotask` with `setTimeout`, the radios appear.

Alternatively, we could refactor a bit so that we don't update the `tabindex` attribute until the element is first connected. That's probably the better approach, but a bit more effort.

Would welcome a PR to swap it to setTimeout in the meantime!

**Comment by asyncLiz** [comment]
Fixed in https://github.com/material-components/material-web/pull/5463
