### ISSUE TITLE
quick attribute on md-dialog

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#5465]
### Description

A `quick` attribute:
```html
<md-dialog quick>...</md-dialog>
```
to open/close the dialog without any animations.

One implementation solution would be to change:
https://github.com/material-components/material-web/blob/6589b2ee4b41c19f4683cbeb2c9457c97c1b434a/dialog/internal/dialog.ts#L76-L86

to
```js
getOpenAnimation() {
  if (this.quick) {
    return {};
  }
  else {
    return DIALOG_DEFAULT_OPEN_ANIMATION;
  }
}

getCloseAnimation() {
  if (this.quick) {
    return {};
  }
  else {
    return DIALOG_DEFAULT_CLOSE_ANIMATION;
  }
}
```

(Waiting the green light)

**Comment by asyncLiz** [comment]
I think a `quick` attribute similar to menus makes sense!

However, I would move it to [`animateDialog()`](https://github.com/material-components/material-web/blob/f2ff86725ccb96347af1881657428e4de1fe0bae/dialog/internal/dialog.ts#L398) so that clients who override `getOpenAnimation`/`getCloseAnimation` do not need to check for `dialog.quick`.

```diff
   private async animateDialog(animation: DialogAnimation) {
+    if (this.quick) {
+      return;
+    }

     const {dialog, scrim, container, headline, content, actions} = this;
     if (!dialog || !scrim || !container || !headline || !content || !actions) {
       return;
     }
     // ...
   }
```
