### ISSUE TITLE
Warning when using md-outlined-text-field with v-model in Vue.js

### ISSUE THREAD

**Issue by pennin-style** [material-components/material-web#5687]
### What is affected?

Other/unknown

### Description

**Describe the bug**

When using `md-outlined-text-field` with `v-model` in a Vue.js application, a warning message is displayed in the console, even though the component seems to be working correctly. 

The warning message is: 
`Element md-outlined-text-field scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information.`

**To Reproduce**
1. Create a Vue.js component that uses `md-outlined-text-field` with `v-model`.
2. Run the application.
3. Open the browser console.
4. When the first character is entered in the `md-outlined-text-field` component, a Warning is displayed in the console.

**Expected behavior**
The warning message should not be displayed.

**Screenshots/Code snippets**
```vue PJOutlinedTextField.vue
<script lang="ts" setup>
import type { MdOutlinedTextField } from '@material/web/textfield/outlined-text-field'

interface Props {
  modelValue: string | number
  error?: boolean
  errorText?: string
  label?: string
  type?: 'text' | 'email' | 'number' | 'password' | 'search' | 'tel' | 'url' | 'textarea'
  prefixText?: string
  suffixText?: string
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '',
  error: false,
  errorText: '',
  label: '',
  type: 'text',
  prefixText: '',
  suffixText: '',
})
const emit = defineEmits<{
  'update:modelValue': [value: string | number]
}>()

const onInput = (e: Event) => {
  const value = (e.target as MdOutlinedTextField)?.value
  emit('update:modelValue', props.type === 'number' && value !== '' && !isNaN(Number(value)) ? Number(value) : value)
}
</script>

<template>
  <md-outlined-text-field
    v-bind="props"
    :value="modelValue"
    @input="onInput"
  />
</template>
```

``` vue PJModalFilterProjects.vue
<script lang="ts" setup>
import { z } from 'zod'
import type { MdDialog } from '@material/web/dialog/dialog.js'
import type { MdFilterChip } from '@material/web/chips/filter-chip.js'
import type { MdSlider } from '@material/web/slider/slider.js'
import type { FilterParams } from '@/interfaces'

…

const {
  value: totalMinutesMin,
  meta: totalMinutesMinMeta,
  errorMessage: totalMinutesMinError,
} = useField<FilterParams['projects']['totalMinutesMin']>('totalMinutesMin')

…

</script>
<template>

…

  <PJOutlinedTextField
    v-model="totalMinutesMin"
    type="number"
    label="分"
    min="0"
    max="59"
    .error="totalMinutesMinMeta.dirty && !totalMinutesMinMeta.valid"
    :error-text="totalMinutesMinError"
    class="is-full"
  />

…

</template>
```

**Environment:**
- OS: macOS 14.5
- Browser: Chrome 127.0.6533.72
- @material/web: 2.0.0
- nuxt 3.12.4
- vue: 3.4.34
- @vee-validate/nuxt: 4.13.2

**Additional context**
We have tried several workarounds, including:
- Using `requestUpdate()` after updating the `value` property of `md-outlined-text-field`.
- Manually triggering an `input` event after updating the `value` property.
- Using `watch` to observe changes to the `v-model` value and update the `md-outlined-text-field` accordingly.

However, none of these solutions have successfully resolved the warning message.

This issue seems to be related to a timing issue between Vue.js's reactivity system and LitElement's rendering cycle.

We would appreciate any guidance or suggestions on how to resolve this issue.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ivpnqt?file=app.vue

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.0.0

### Browser/OS/Node environment

- OS: macOS 14.5
- Browser: Chrome 127.0.6533.72
- @material/web: 2.0.0
- nuxt 3.12.4
- vue: 3.4.34
- @vee-validate/nuxt: 4.13.2

**Comment by asyncLiz** [comment]
Thanks for the detailed bug report!

The warning appears because your props type for `:value` is `modelValue: string | number`, and `HTMLInputElement.value` is supposed to only be a string. When you set the value to a number, it triggers [this fail-safe that re-sets the value](https://github.com/material-components/material-web/blob/7231e51e9f9d307cdbbb58817ff798e7e7d29ff8/textfield/internal/text-field.ts#L539-L547) to a string.

```js
textField.value = 5;
console.log(textField.value); // 5, a number
// Text field updates, sees that input.value is a string '5', which doesn't match the number 5
await textField.updateComplete;
console.log(textField.value); // '5', a string
```

This warning is safe to ignore, but it could lead to some unexpected type bugs.

Some options to consider that will remove the warning and be more type-safe:

- Create a computed property that converts `modelValue` to a string, and bind `:value="modelValueAsString"` instead of the possibly-a-number `modelValue`.
- You can also bind to `:valueAsNumber`, which gets and sets a `Number` version of the value when the input type is numeric.
- [This Vue forms guide](https://v2.vuejs.org/v2/guide/forms.html#number) may also be relevant, which recommends using `v-model.number` when binding to numeric inputs. You may be able to take advantage of that when using your text field wrapper Vue component that has v-model support.

Closing since this is WAI, but feel free to continue the conversation!

**Comment by pennin-style** [comment]
Dear @asyncLiz

Thank you for your prompt and detailed explanation.
I had forgotten that `HTMLInputElement.value` supports only string type.

The first method you described resolved the warning without any problems.

Thank you very much for your help.
