### ISSUE TITLE
bug(textfield): min and max attributes only accepts string

### ISSUE THREAD

**Issue by zZHorizonZz** [material-components/material-web#5732]
### What is affected?

Component

### Description

The `min` and `max` attributes in the `textfield` component only support values of type `string` or `undefined`, but the actual HTML input element supports values of type `string`, `number`, or `undefined`.

### Reproduction

None

### Workaround

None

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.2.0

### Browser/OS/Node environment

Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Enterprise
  Available memory (MB): 32394
  Available CPU cores: 8
Binaries:
  Node: 21.7.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A

**Comment by asyncLiz** [comment]
This is intentional since the native input min/max attributes serialize all values as strings. You can see this when calling the getter of the input properties after setting them to a number.

Right now we don't automatically coerce values to a string like the native input does. https://github.com/material-components/material-web/issues/5357 tracks adding automatic type coercion.
