### ISSUE TITLE
mwc-textfield and mwc-textarea RTL support

### ISSUE THREAD

**Issue by MhfDeveloper** [material-components/material-web#858]
**I'm submitting a:**

- [ x ] bug report
- [ ] feature request

**What OS are you using?**
Fedora v31

**What browser(s) is this bug affecting:**
Chrome & Firefox

**Expected behavior:**
RTL support

I added **dir=rtl** to html tag and the result was:
![mwc-textfield-rtl-issue](https://user-images.githubusercontent.com/60940446/74267483-5f818180-4d1b-11ea-8fff-464da8100990.png)

**Comment by dfreedm** [comment]
Yep, there are a few things we need to do to fix the RTL styling in WC wrappers here.
Thanks for the screenshots!

**Comment by jameelappsintegra** [comment]
Can we override the mwc-noutched-outline component to render the outline in RTL.
https://www.npmjs.com/package/@material/mwc-notched-outline

**Comment by brownieboy** [comment]
For the floating labels issue, there are two styles that are interfering with them moving over the right when the `dir="rtl"` attribute is applied.  These are:
```css
.mdc-text-field--filled .mdc-floating-label {
    left: 16px;
    right: initial;
}
```

and
```css
.mdc-floating-label {
    left: 0;
}
```

Unfortunately, these are in a "constructed stylesheet" (i.e transpiled) and my knowldege of SASS is not good enough to trace the styles to their source.

Here's animated GIF of me altering the [TextField Demo page](https://material-components.github.io/material-components-web-components/demos/textfield/) to demonstrate the issue and what happens when I remove these styles.

First, I add the`dir="rtl"` attribute to the Body tag.   Then I'll deactivate the two styles above, and you'll see the labels move from left to right - some of them, anyway! ;-).  Hopefully, somebody with more knowledge of the source code and SASS can work out where these styles are coming from.

![mvc-rtl-label-styles](https://user-images.githubusercontent.com/1781909/100577772-05e35580-3335-11eb-8cc4-1934fca77074.gif)

**Comment by davie-robertson** [comment]
is there any chance we can prioritize this?

**Comment by brownieboy** [comment]
I've made a little progress with the floating labels on the TextField, TextArea and Select components in [a fork of the repo](https://github.com/brownieboy/material-components-web-components/tree/bugfix/rtl%23858).   Some of the variations, at least.  The outlined versions of TextField are going to take a bit more work due to the way their segmented with `<mwc-notched-outline>` components.

And while there are RTL-friendly versions of some CSS properties - e.g `margin-inline-start` instead of `margin-left` - which I've used here, there are still many more properties that _don't_ have such alternatives.  Yes, you can use a `[dir="rtl"]` selector in your CSS, but for the Shadow DOM that means passing in the `dir` attribute to your component as a prop because your Shadow DOM CSS can't see the `dir` prop in the main DOM.   That's doable, but a pain.

![mwc-text-rtl-initial-fixes](https://user-images.githubusercontent.com/1781909/101592099-c954df80-3a41-11eb-9969-09cdb53ed08a.gif)

**Comment by jameelappsintegra** [comment]
Please overwrite the css in mdc-noutched-outline

for outline trailing
![image](https://user-images.githubusercontent.com/47351791/101596082-e7a0e800-3a0d-11eb-9a1d-3cf61da118f1.png)

for outline leading
![image](https://user-images.githubusercontent.com/47351791/101596245-2c2c8380-3a0e-11eb-9df0-7b8e07e52fd9.png)
![image](https://user-images.githubusercontent.com/47351791/101596536-b2e16080-3a0e-11eb-9dce-30db4c08fe7c.png)

**Comment by davie-robertson** [comment]
can we move this to Severity: High as we're unable to use this on international projects; there's over 300 Million Arabic speakers in the world, not including other Semitic languages that use RTL flowing text.

**Comment by asyncLiz** [comment]
Fixed in M3
